name: simple_habits
description: A new Flutter project.

publish_to: 'none'

version: 1.0.5+5

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any
  weekday_selector: any
  flutter_bloc: any
  flutter_local_notifications: any
  flutter_slidable: any
  shared_preferences: any
  sqflite: any
  path_provider: any
  url_launcher: any
  share_plus: any  # Use this instead of share

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/img/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
  uses-material-design: true
